version: "2"

run:
  timeout: 5m
  tests: true

formatters:
  enable:
    - gofmt

linters:
  settings:
    gocyclo:
      min-complexity: 22
  enable:
    - govet
    - staticcheck
    - gocyclo

issues:
  exclude-dirs:
    - vendor
    - .git
