version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: protoc-gen-go-http-server-interface
    ldflags:
      - -s -w
      - -X github.com/farhaan/protoc-gen-go-http-server-interface/version.Version={{.Version}}
      - -X github.com/farhaan/protoc-gen-go-http-server-interface/version.GitCommit={{.Commit}}
      - -X github.com/farhaan/protoc-gen-go-http-server-interface/version.BuildTime={{.Date}}

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
