// Package httpinterface implements HTTP interface generation for protocol buffers.
package httpinterface

import (
	"bytes"
	_ "embed"
	"fmt"
	"go/token"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"sync"
	"text/template"
	"unicode/utf8"

	"github.com/farhaan/protoc-gen-go-http-server-interface/httpinterface/parser"
	"google.golang.org/protobuf/proto"
	descriptor "google.golang.org/protobuf/types/descriptorpb"
	plugin "google.golang.org/protobuf/types/pluginpb"
)

// Templates
var (
	//go:embed templates/header-template.go.tmpl
	headerTemplate string
	//go:embed templates/service-template.go.tmpl
	serviceTemplate string
)

// validateGoSourceString returns an error if s contains bytes that would make
// generated Go source unparseable: invalid UTF-8 or ASCII control characters.
// URL patterns and HTTP methods from proto annotations are always printable
// ASCII, so this catches inputs outside the generator's designed use case.
func validateGoSourceString(field, s string) error {
	if !utf8.ValidString(s) {
		return fmt.Errorf("invalid UTF-8 in %s: %q", field, s)
	}
	for _, r := range s {
		if r < 0x20 || r == 0x7f {
			return fmt.Errorf("%s contains control character %U: %q", field, r, s)
		}
	}
	return nil
}

// templateFuncs returns the shared template.FuncMap used by all generators.
func templateFuncs() template.FuncMap {
	return template.FuncMap{
		"lower": strings.ToLower,
		"title": func(s string) string {
			if s == "" {
				return ""
			}
			return strings.ToUpper(s[:1]) + s[1:]
		},
		"httpMethod": toHTTPMethodConstant,
		// goQuote returns a properly escaped Go string literal (including surrounding
		// double quotes) using strconv.Quote. Use this whenever a string value is
		// embedded inside Go source code generated by a template.
		"goQuote": strconv.Quote,
	}
}

// toHTTPMethodConstant converts an HTTP method string to a net/http constant name.
func toHTTPMethodConstant(method string) string {
	switch method {
	case "GET":
		return "http.MethodGet"
	case "POST":
		return "http.MethodPost"
	case "PUT":
		return "http.MethodPut"
	case "DELETE":
		return "http.MethodDelete"
	case "PATCH":
		return "http.MethodPatch"
	case "HEAD":
		return "http.MethodHead"
	case "OPTIONS":
		return "http.MethodOptions"
	case "TRACE":
		return "http.MethodTrace"
	case "CONNECT":
		return "http.MethodConnect"
	default:
		// For custom methods, return a properly escaped Go string literal.
		return strconv.Quote(method)
	}
}

// bufPool reuses bytes.Buffer instances across GenerateCode calls.
var bufPool = sync.Pool{New: func() any { return new(bytes.Buffer) }}

// Generator is the httpinterface code generator.
type Generator struct {
	// ParsedTemplates contains the parsed templates for code generation
	ParsedTemplates *template.Template
	// Options contains the plugin options
	Options *Options
	// HTTPRuleExtractor extracts HTTP rules from method descriptors
	HTTPRuleExtractor HTTPRuleExtractor
	// PathParamExtractor extracts path parameters from patterns
	PathParamExtractor PathParamExtractor
	// PathPatternConverter converts path patterns
	PathPatternConverter PathPatternConverter
	// SupportsEditions indicates if this generator supports editions
	SupportsEditions bool
}

// ServiceData contains the data for a service definition.
type ServiceData struct {
	PackageName string
	Services    []ServiceInfo
}

// ServiceInfo contains information about a service.
type ServiceInfo struct {
	Name    string
	Methods []MethodInfo
}

// MethodInfo contains information about a method.
type MethodInfo struct {
	Name       string
	InputType  string
	OutputType string
	HTTPRules  []parser.HTTPRule
}

// New creates a new httpinterface generator with an optional custom HTTP rule extractor.
// If no extractor is provided, uses the default extractHTTPRules.
func New(httpExtractor ...HTTPRuleExtractor) *Generator {
	// Parse the templates
	tmpl := template.New("httpinterface").Funcs(templateFuncs())

	// Parse header template
	tmpl = template.Must(tmpl.New("header").Parse(headerTemplate))

	// Parse service template
	tmpl = template.Must(tmpl.New("service").Parse(serviceTemplate))

	// Set up defaults
	var extractor HTTPRuleExtractor = extractHTTPRules
	if len(httpExtractor) > 0 {
		extractor = httpExtractor[0]
	}

	return &Generator{
		ParsedTemplates:      tmpl,
		Options:              &Options{},
		HTTPRuleExtractor:    extractor,
		PathParamExtractor:   extractPathParams,
		PathPatternConverter: convertPathPattern,
		SupportsEditions:     true,
	}
}

// NewWith creates a new generator with all custom dependencies.
func NewWith(httpExtractor HTTPRuleExtractor, pathExtractor PathParamExtractor,
	converter PathPatternConverter) *Generator {
	// Parse the templates
	tmpl := template.New("httpinterface").Funcs(templateFuncs())

	// Parse header template
	tmpl = template.Must(tmpl.New("header").Parse(headerTemplate))

	// Parse service template
	tmpl = template.Must(tmpl.New("service").Parse(serviceTemplate))

	return &Generator{
		ParsedTemplates:      tmpl,
		Options:              &Options{},
		HTTPRuleExtractor:    httpExtractor,
		PathParamExtractor:   pathExtractor,
		PathPatternConverter: converter,
		SupportsEditions:     true,
	}
}

// Generate generates the HTTP interface code.
// It is safe to call concurrently on the same Generator; options are parsed
// locally per call and never written to shared state.
func (g *Generator) Generate(req *plugin.CodeGeneratorRequest) *plugin.CodeGeneratorResponse {
	resp := new(plugin.CodeGeneratorResponse)

	// Parse options locally so concurrent Generate calls don't race on g.Options.
	opts, err := ParseOptions(req.GetParameter())
	if err != nil {
		resp.Error = proto.String(fmt.Sprintf("invalid options: %v", err))
		return resp
	}

	// Editions support: enabled globally or per-request via options.
	supportsEditions := g.SupportsEditions || opts.Editions

	// Declare support for protobuf features.
	supportedFeatures := uint64(plugin.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
	if supportsEditions {
		supportedFeatures |= uint64(plugin.CodeGeneratorResponse_FEATURE_SUPPORTS_EDITIONS)
	}
	resp.SupportedFeatures = proto.Uint64(supportedFeatures)

	if supportsEditions {
		resp.MinimumEdition = proto.Int32(int32(descriptor.Edition_EDITION_PROTO3))
		resp.MaximumEdition = proto.Int32(int32(descriptor.Edition_EDITION_2023))
	}

	// Process each proto file.
	for _, file := range req.ProtoFile {
		if outputFile, err := g.processFile(file, req.FileToGenerate, opts); err != nil {
			resp.Error = proto.String(err.Error())
			return resp
		} else if outputFile != nil {
			resp.File = append(resp.File, outputFile)
		}
	}

	return resp
}

// processFile processes a single proto file and returns an output file if generation is needed.
func (g *Generator) processFile(
	file *descriptor.FileDescriptorProto,
	filesToGenerate []string,
	opts *Options,
) (*plugin.CodeGeneratorResponse_File, error) {
	if !g.shouldGenerate(file.GetName(), filesToGenerate) {
		return nil, nil
	}

	// Check if the file has any services with HTTP annotations
	if !g.hasHTTPRules(file) {
		return nil, nil
	}

	// Prepare the data for code generation
	data := g.buildServiceData(file)
	if len(data.Services) == 0 {
		return nil, nil
	}

	// Generate code
	content, err := g.GenerateCode(data)
	if err != nil {
		return nil, fmt.Errorf("error generating code for %s: %v", file.GetName(), err)
	}

	// Create output file
	filename := g.getOutputFilename(file.GetName(), opts)
	outputFile := &plugin.CodeGeneratorResponse_File{
		Name:    proto.String(filename),
		Content: proto.String(content),
	}

	// Handle source_relative paths option
	g.applySourceRelativePath(outputFile, file.GetName(), opts)

	return outputFile, nil
}

// applySourceRelativePath adjusts the output filename when paths=source_relative is set.
// It prefixes the output filename with the proto file's directory.
func (g *Generator) applySourceRelativePath(
	outputFile *plugin.CodeGeneratorResponse_File,
	protoFileName string,
	opts *Options,
) {
	if opts.PathsSourceRelative {
		dir := filepath.Dir(protoFileName)
		if dir != "." {
			filename := filepath.Base(outputFile.GetName())
			outputFile.Name = proto.String(filepath.Join(dir, filename))
		}
	}
}

// shouldGenerate returns whether code should be generated for the given file.
func (g *Generator) shouldGenerate(file string, filesToGenerate []string) bool {
	return slices.Contains(filesToGenerate, file)
}

// hasHTTPRules returns whether the file has any services with HTTP annotations.
func (g *Generator) hasHTTPRules(file *descriptor.FileDescriptorProto) bool {
	for _, service := range file.Service {
		for _, method := range service.Method {
			rules := g.HTTPRuleExtractor(method)
			if len(rules) > 0 {
				return true
			}
		}
	}
	return false
}

// buildServiceData builds the service data for code generation.
func (g *Generator) buildServiceData(file *descriptor.FileDescriptorProto) *ServiceData {
	data := &ServiceData{
		PackageName: g.getPackageName(file),
		Services:    make([]ServiceInfo, 0, len(file.Service)),
	}

	for _, service := range file.Service {
		serviceInfo := ServiceInfo{
			Name:    service.GetName(),
			Methods: make([]MethodInfo, 0, len(service.Method)),
		}

		for _, method := range service.Method {
			httpRules := g.HTTPRuleExtractor(method)
			if len(httpRules) == 0 {
				continue
			}

			methodInfo := MethodInfo{
				Name:       method.GetName(),
				InputType:  g.getTypeName(method.GetInputType()),
				OutputType: g.getTypeName(method.GetOutputType()),
				HTTPRules:  httpRules,
			}

			// Process HTTP rules
			for i := range methodInfo.HTTPRules {
				rule := &methodInfo.HTTPRules[i]
				rule.PathParams = g.PathParamExtractor(rule.Pattern)
				rule.Pattern = g.PathPatternConverter(rule.Pattern)
			}

			serviceInfo.Methods = append(serviceInfo.Methods, methodInfo)
		}

		if len(serviceInfo.Methods) > 0 {
			data.Services = append(data.Services, serviceInfo)
		}
	}

	return data
}

// GenerateCode generates the code from templates.
func (g *Generator) GenerateCode(data *ServiceData) (string, error) {
	// Validate that names are valid Go identifiers so the output is always
	// syntactically correct Go source.
	if !token.IsIdentifier(data.PackageName) {
		return "", fmt.Errorf("invalid Go identifier for package name: %q", data.PackageName)
	}
	for _, svc := range data.Services {
		if !token.IsIdentifier(svc.Name) {
			return "", fmt.Errorf("invalid Go identifier for service name: %q", svc.Name)
		}
		for _, m := range svc.Methods {
			if !token.IsIdentifier(m.Name) {
				return "", fmt.Errorf("invalid Go identifier for method name: %q", m.Name)
			}
			for _, rule := range m.HTTPRules {
				// Patterns and HTTP methods are embedded in Go source comments and string
				// literals. They must be valid UTF-8 (Go source files must be UTF-8) and
				// must not contain control characters (null bytes, newlines, etc.) which
				// are never valid in URLs and would break the generated source.
				if err := validateGoSourceString("pattern", rule.Pattern); err != nil {
					return "", err
				}
				if err := validateGoSourceString("HTTP method", rule.Method); err != nil {
					return "", err
				}
			}
		}
	}

	buf := bufPool.Get().(*bytes.Buffer)
	buf.Reset()
	defer bufPool.Put(buf)

	// Execute header template
	if err := g.ParsedTemplates.ExecuteTemplate(buf, "header", data); err != nil {
		return "", fmt.Errorf("failed to execute header template: %v", err)
	}

	// Execute service template for each service
	for _, service := range data.Services {
		if err := g.ParsedTemplates.ExecuteTemplate(buf, "service", service); err != nil {
			return "", fmt.Errorf("failed to execute service template for %s: %v", service.Name, err)
		}
	}

	return buf.String(), nil
}

// getOutputFilename returns the output filename for a proto file.
func (g *Generator) getOutputFilename(protoFilename string, opts *Options) string {
	base := filepath.Base(protoFilename)
	filename := strings.TrimSuffix(base, ".proto")

	if opts.OutputPrefix != "" {
		filename = opts.OutputPrefix + "_" + filename
	} else {
		filename = filename + "_http"
	}

	return filename + ".pb.go"
}

// getPackageName returns the Go package name for a proto file.
func (g *Generator) getPackageName(file *descriptor.FileDescriptorProto) string {
	// Use go_package option if available
	if goPackage := file.GetOptions().GetGoPackage(); goPackage != "" {
		return g.extractPackageFromGoPackage(goPackage)
	}

	// Fall back to proto package name
	return g.extractPackageFromProtoPackage(file.GetPackage())
}

// extractPackageFromGoPackage extracts the Go package name from go_package option.
//
// Strategy:
//   - "github.com/foo/bar;baz" → "baz"   (explicit name after semicolon)
//   - "github.com/foo/bar"     → "bar"   (last path segment)
//   - "bar"                    → "bar"   (as-is)
func (g *Generator) extractPackageFromGoPackage(goPackage string) string {
	if idx := strings.LastIndex(goPackage, ";"); idx >= 0 {
		return goPackage[idx+1:]
	}
	if idx := strings.LastIndex(goPackage, "/"); idx >= 0 {
		return goPackage[idx+1:]
	}
	return goPackage
}

// extractPackageFromProtoPackage derives a Go package name from a proto package.
//
// Strategy:
//   - 1 segment:  "api"             → "api"
//   - 2 segments: "api.v1"          → "apiv1"    (join all)
//   - 3+ segments: "api.core.v1"    → "corev1"   (join last 2)
//
// The last-two strategy for 3+ segments assumes the final segments are
// the most specific (e.g., service name + version), while earlier segments
// are organizational prefixes that can be dropped.
func (g *Generator) extractPackageFromProtoPackage(protoPackage string) string {
	if protoPackage == "" {
		return ""
	}

	parts := strings.Split(protoPackage, ".")
	switch len(parts) {
	case 1:
		return parts[0]
	case 2:
		return strings.Join(parts, "")
	default:
		lastTwo := parts[len(parts)-2:]
		return strings.Join(lastTwo, "")
	}
}

// getTypeName returns the simple type name from a fully qualified type name.
func (g *Generator) getTypeName(typeName string) string {
	if typeName == "" {
		return ""
	}
	parts := strings.Split(typeName, ".")
	return parts[len(parts)-1]
}
