// Code generated by protoc-gen-go-http-server-interface. DO NOT EDIT.
package pb

import (
	"net/http"
	"strings"
)

// Middleware represents a middleware function that wraps an http.Handler
type Middleware func(http.Handler) http.Handler

// Routes defines methods for registering routes
type Routes interface {
	// HandleFunc registers a handler function for the given method and pattern
	HandleFunc(method, pattern string, handler http.HandlerFunc, middlewares ...Middleware)
	
	// Group creates a new RouteGroup with the given prefix and optional middlewares
	Group(prefix string, middlewares ...Middleware) *RouteGroup
	
	// Use applies middlewares to all routes registered after this call
	Use(middlewares ...Middleware) *RouteGroup
}

// RouteGroup represents a group of routes with a common prefix and middleware
type RouteGroup struct {
	prefix          string
	middlewares     []Middleware
	routes          []routeDef
	mux             *http.ServeMux
}

// routeDef stores a route definition before it's registered with the mux
type routeDef struct {
	method      string
	pattern     string
	handler     http.Handler
}

// NewRouter creates a new router with an optional mux
// If mux is nil, a new http.ServeMux will be created
func NewRouter(mux *http.ServeMux) *RouteGroup {
	if mux == nil {
		mux = http.NewServeMux()
	}
	
	return &RouteGroup{
		prefix:       "",
		middlewares:  []Middleware{},
		routes:       []routeDef{},
		mux:          mux,
	}
}

// DefaultRouter creates a new router with a new ServeMux
// This function exists for backward compatibility
func DefaultRouter() *RouteGroup {
	return NewRouter(nil)
}

// Group creates a new RouteGroup with the given prefix and optional middlewares
func (g *RouteGroup) Group(prefix string, middlewares ...Middleware) *RouteGroup {
	// Ensure prefix starts with /
	if prefix != "" && !strings.HasPrefix(prefix, "/") {
		prefix = "/" + prefix
	}
	
	// If prefix is just "/", don't add it again
	if g.prefix == "/" && prefix == "/" {
		prefix = "/"
	} else if prefix == "/" {
		prefix = g.prefix
	} else {
		prefix = g.prefix + prefix
	}
	
	// Combine parent and new middlewares, filtering out nils
	combinedMiddlewares := make([]Middleware, 0, len(g.middlewares)+len(middlewares))
	for _, mw := range g.middlewares {
		if mw != nil {
			combinedMiddlewares = append(combinedMiddlewares, mw)
		}
	}
	for _, mw := range middlewares {
		if mw != nil {
			combinedMiddlewares = append(combinedMiddlewares, mw)
		}
	}

	return &RouteGroup{
		prefix:       prefix,
		middlewares:  combinedMiddlewares,
		routes:       []routeDef{}, // Each group gets its own routes slice
		mux:          g.mux,        // Share the same mux
	}
}

// Use applies middlewares to all routes registered after this call
func (g *RouteGroup) Use(middlewares ...Middleware) *RouteGroup {
	// Filter out nil middlewares before appending
	for _, mw := range middlewares {
		if mw != nil {
			g.middlewares = append(g.middlewares, mw)
		}
	}
	return g
}

// HandleFunc registers a handler function for the given method and pattern
func (g *RouteGroup) HandleFunc(method, pattern string, handler http.HandlerFunc, middlewares ...Middleware) {
	// Apply the prefix to the pattern
	fullPattern := g.prefix
	if g.prefix == "/" && pattern != "/" {
		fullPattern = pattern
	} else if pattern == "/" {
		fullPattern = g.prefix
	} else {
		fullPattern = g.prefix + pattern
	}

	// Apply middleware chain to the handler
	var finalHandler http.Handler = handler

	// Filter and collect route-specific middlewares
	validMiddlewares := make([]Middleware, 0, len(middlewares))
	for _, mw := range middlewares {
		if mw != nil {
			validMiddlewares = append(validMiddlewares, mw)
		}
	}

	// Apply route-specific middlewares first (innermost)
	for i := len(validMiddlewares) - 1; i >= 0; i-- {
		finalHandler = validMiddlewares[i](finalHandler)
	}

	// Apply group middlewares (outermost)
	for i := len(g.middlewares) - 1; i >= 0; i-- {
		mw := g.middlewares[i]
		if mw != nil {
			finalHandler = mw(finalHandler)
		}
	}
	
	// Store and register the route definition
	routeDefinition := routeDef{
		method:   method,
		pattern:  fullPattern,
		handler:  finalHandler,
	}
	g.routes = append(g.routes, routeDefinition)

	// Register with mux if available
	if g.mux != nil {
		routeDefinitionKey := routeDefinition.method + " " + routeDefinition.pattern
		g.mux.Handle(routeDefinitionKey, routeDefinition.handler)
	}

}

func (g RouteGroup) GetRoutes() []string {
	routes := make([]string, 0, len(g.routes))
	for _, route := range g.routes {
		routes = append(routes, route.method+" "+route.pattern)
	}
	return routes
}


// ServeHTTP implements the http.Handler interface
func (g *RouteGroup) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if g.mux != nil {
		g.mux.ServeHTTP(w, r)
	} else {
		http.NotFound(w, r)
	}
}// TaskServiceHandler is the interface for TaskService HTTP handlers
type TaskServiceHandler interface {
    HandleCreateTask(w http.ResponseWriter, r *http.Request)
    HandleGetTask(w http.ResponseWriter, r *http.Request)
    HandleUpdateTask(w http.ResponseWriter, r *http.Request)
    HandleDeleteTask(w http.ResponseWriter, r *http.Request)
    HandleListTasks(w http.ResponseWriter, r *http.Request)
    HandleCompleteTask(w http.ResponseWriter, r *http.Request)
    HandleGetTasksByProject(w http.ResponseWriter, r *http.Request)
    HandleAssignTask(w http.ResponseWriter, r *http.Request)
}

// RegisterTaskServiceRoutes registers HTTP routes for TaskService
func RegisterTaskServiceRoutes(r Routes, handler TaskServiceHandler) {
	if r == nil || handler == nil {
		return
	}
    r.HandleFunc(http.MethodPost, "/api/v1/tasks", handler.HandleCreateTask)
    r.HandleFunc(http.MethodGet, "/api/v1/tasks/{task_id}", handler.HandleGetTask)
    r.HandleFunc(http.MethodPut, "/api/v1/tasks/{task_id}", handler.HandleUpdateTask)
    r.HandleFunc(http.MethodPatch, "/api/v1/tasks/{task_id}", handler.HandleUpdateTask)
    r.HandleFunc(http.MethodDelete, "/api/v1/tasks/{task_id}", handler.HandleDeleteTask)
    r.HandleFunc(http.MethodGet, "/api/v1/tasks", handler.HandleListTasks)
    r.HandleFunc(http.MethodPost, "/api/v1/tasks/{task_id}/complete", handler.HandleCompleteTask)
    r.HandleFunc(http.MethodGet, "/api/v1/projects/{project_id}/tasks", handler.HandleGetTasksByProject)
    r.HandleFunc(http.MethodPost, "/api/v1/projects/{project_id}/tasks/{task_id}/assign/{user_id}", handler.HandleAssignTask)
}

// RegisterTaskServiceRoutes is a method on RouteGroup to register all TaskService routes
func (g *RouteGroup) RegisterTaskServiceRoutes(handler TaskServiceHandler) {
    RegisterTaskServiceRoutes(g, handler)
}
// RegisterCreateTaskRoute is a helper that registers the CreateTask handler
// This registers all HTTP bindings for this method (1 binding(s))
func RegisterCreateTaskRoute(r Routes, handler TaskServiceHandler, middlewares ...Middleware) {
	if r == nil || handler == nil {
		return
	}
    r.HandleFunc(http.MethodPost, "/api/v1/tasks", handler.HandleCreateTask, middlewares...)
}

// RegisterCreateTask is a method on RouteGroup to register the CreateTask handler
func (g *RouteGroup) RegisterCreateTask(handler TaskServiceHandler, middlewares ...Middleware) {
    RegisterCreateTaskRoute(g, handler, middlewares...)
}
// RegisterGetTaskRoute is a helper that registers the GetTask handler
// This registers all HTTP bindings for this method (1 binding(s))
func RegisterGetTaskRoute(r Routes, handler TaskServiceHandler, middlewares ...Middleware) {
	if r == nil || handler == nil {
		return
	}
    r.HandleFunc(http.MethodGet, "/api/v1/tasks/{task_id}", handler.HandleGetTask, middlewares...)
}

// RegisterGetTask is a method on RouteGroup to register the GetTask handler
func (g *RouteGroup) RegisterGetTask(handler TaskServiceHandler, middlewares ...Middleware) {
    RegisterGetTaskRoute(g, handler, middlewares...)
}
// RegisterUpdateTaskRoute is a helper that registers the UpdateTask handler
// This registers all HTTP bindings for this method (2 binding(s))
func RegisterUpdateTaskRoute(r Routes, handler TaskServiceHandler, middlewares ...Middleware) {
	if r == nil || handler == nil {
		return
	}
    r.HandleFunc(http.MethodPut, "/api/v1/tasks/{task_id}", handler.HandleUpdateTask, middlewares...)
    r.HandleFunc(http.MethodPatch, "/api/v1/tasks/{task_id}", handler.HandleUpdateTask, middlewares...)
}

// RegisterUpdateTask is a method on RouteGroup to register the UpdateTask handler
func (g *RouteGroup) RegisterUpdateTask(handler TaskServiceHandler, middlewares ...Middleware) {
    RegisterUpdateTaskRoute(g, handler, middlewares...)
}
// RegisterDeleteTaskRoute is a helper that registers the DeleteTask handler
// This registers all HTTP bindings for this method (1 binding(s))
func RegisterDeleteTaskRoute(r Routes, handler TaskServiceHandler, middlewares ...Middleware) {
	if r == nil || handler == nil {
		return
	}
    r.HandleFunc(http.MethodDelete, "/api/v1/tasks/{task_id}", handler.HandleDeleteTask, middlewares...)
}

// RegisterDeleteTask is a method on RouteGroup to register the DeleteTask handler
func (g *RouteGroup) RegisterDeleteTask(handler TaskServiceHandler, middlewares ...Middleware) {
    RegisterDeleteTaskRoute(g, handler, middlewares...)
}
// RegisterListTasksRoute is a helper that registers the ListTasks handler
// This registers all HTTP bindings for this method (1 binding(s))
func RegisterListTasksRoute(r Routes, handler TaskServiceHandler, middlewares ...Middleware) {
	if r == nil || handler == nil {
		return
	}
    r.HandleFunc(http.MethodGet, "/api/v1/tasks", handler.HandleListTasks, middlewares...)
}

// RegisterListTasks is a method on RouteGroup to register the ListTasks handler
func (g *RouteGroup) RegisterListTasks(handler TaskServiceHandler, middlewares ...Middleware) {
    RegisterListTasksRoute(g, handler, middlewares...)
}
// RegisterCompleteTaskRoute is a helper that registers the CompleteTask handler
// This registers all HTTP bindings for this method (1 binding(s))
func RegisterCompleteTaskRoute(r Routes, handler TaskServiceHandler, middlewares ...Middleware) {
	if r == nil || handler == nil {
		return
	}
    r.HandleFunc(http.MethodPost, "/api/v1/tasks/{task_id}/complete", handler.HandleCompleteTask, middlewares...)
}

// RegisterCompleteTask is a method on RouteGroup to register the CompleteTask handler
func (g *RouteGroup) RegisterCompleteTask(handler TaskServiceHandler, middlewares ...Middleware) {
    RegisterCompleteTaskRoute(g, handler, middlewares...)
}
// RegisterGetTasksByProjectRoute is a helper that registers the GetTasksByProject handler
// This registers all HTTP bindings for this method (1 binding(s))
func RegisterGetTasksByProjectRoute(r Routes, handler TaskServiceHandler, middlewares ...Middleware) {
	if r == nil || handler == nil {
		return
	}
    r.HandleFunc(http.MethodGet, "/api/v1/projects/{project_id}/tasks", handler.HandleGetTasksByProject, middlewares...)
}

// RegisterGetTasksByProject is a method on RouteGroup to register the GetTasksByProject handler
func (g *RouteGroup) RegisterGetTasksByProject(handler TaskServiceHandler, middlewares ...Middleware) {
    RegisterGetTasksByProjectRoute(g, handler, middlewares...)
}
// RegisterAssignTaskRoute is a helper that registers the AssignTask handler
// This registers all HTTP bindings for this method (1 binding(s))
func RegisterAssignTaskRoute(r Routes, handler TaskServiceHandler, middlewares ...Middleware) {
	if r == nil || handler == nil {
		return
	}
    r.HandleFunc(http.MethodPost, "/api/v1/projects/{project_id}/tasks/{task_id}/assign/{user_id}", handler.HandleAssignTask, middlewares...)
}

// RegisterAssignTask is a method on RouteGroup to register the AssignTask handler
func (g *RouteGroup) RegisterAssignTask(handler TaskServiceHandler, middlewares ...Middleware) {
    RegisterAssignTaskRoute(g, handler, middlewares...)
}