// Code generated by protoc-gen-go-http-server-interface. DO NOT EDIT.
package pb

import (
	"errors"
	"net/http"
	"strings"
)

// Middleware represents a middleware function that wraps an http.Handler.
type Middleware func(http.Handler) http.Handler

// Routes defines the minimal interface for route registration.
// This interface is intentionally minimal to maximize compatibility with
// standard library and third-party routers (chi, gorilla/mux, etc.).
type Routes interface {
	// HandleFunc registers a handler function for the given method and pattern.
	HandleFunc(method, pattern string, handler http.HandlerFunc)
}

// Router extends Routes with grouping and middleware support.
type Router interface {
	Routes
	// Group creates a sub-router with the given prefix.
	Group(prefix string, middlewares ...Middleware) Router
	// Use appends middlewares to the chain.
	Use(middlewares ...Middleware) Router
}

// RouteGroup implements Router using http.ServeMux.
type RouteGroup struct {
	mux         *http.ServeMux
	prefix      string
	middlewares []Middleware
	routes      []string
}

// NewRouter creates a new router with an optional mux.
// If mux is nil, a new http.ServeMux will be created.
func NewRouter(mux *http.ServeMux) *RouteGroup {
	if mux == nil {
		mux = http.NewServeMux()
	}
	return &RouteGroup{
		mux:         mux,
		prefix:      "",
		middlewares: nil,
		routes:      []string{},
	}
}

// Mux returns the underlying http.ServeMux.
func (g *RouteGroup) Mux() *http.ServeMux {
	return g.mux
}

// joinPath safely joins URL path segments.
func joinPath(base, path string) string {
	if path == "" || path == "/" {
		return base
	}
	if base == "" || base == "/" {
		return path
	}
	return strings.TrimSuffix(base, "/") + "/" + strings.TrimPrefix(path, "/")
}

// Group creates a new RouteGroup with the given prefix and optional middlewares.
func (g *RouteGroup) Group(prefix string, middlewares ...Middleware) Router {
	// Ensure prefix starts with /
	if prefix != "" && !strings.HasPrefix(prefix, "/") {
		prefix = "/" + prefix
	}

	return &RouteGroup{
		mux:         g.mux,
		prefix:      joinPath(g.prefix, prefix),
		middlewares: appendMiddlewares(g.middlewares, middlewares),
		routes:      []string{},
	}
}

// Use appends middlewares to all routes registered after this call.
func (g *RouteGroup) Use(middlewares ...Middleware) Router {
	g.middlewares = appendMiddlewares(g.middlewares, middlewares)
	return g
}

// HandleFunc registers a handler function for the given method and pattern.
// Group middlewares are automatically applied to the handler.
func (g *RouteGroup) HandleFunc(method, pattern string, handler http.HandlerFunc) {
	fullPattern := joinPath(g.prefix, pattern)
	finalHandler := applyMiddlewares(handler, g.middlewares)
	routeKey := method + " " + fullPattern
	g.mux.Handle(routeKey, finalHandler)
	g.routes = append(g.routes, routeKey)
}

// GetRoutes returns all registered routes for this group.
func (g *RouteGroup) GetRoutes() []string {
	return g.routes
}

// ServeHTTP implements the http.Handler interface.
func (g *RouteGroup) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	g.mux.ServeHTTP(w, r)
}

// appendMiddlewares combines parent and new middlewares, filtering out nils.
func appendMiddlewares(parent, additional []Middleware) []Middleware {
	result := make([]Middleware, 0, len(parent)+len(additional))
	for _, mw := range parent {
		if mw != nil {
			result = append(result, mw)
		}
	}
	for _, mw := range additional {
		if mw != nil {
			result = append(result, mw)
		}
	}
	return result
}

// applyMiddlewares wraps handler with the given middlewares (outermost first).
func applyMiddlewares(handler http.Handler, middlewares []Middleware) http.Handler {
	for i := len(middlewares) - 1; i >= 0; i-- {
		if middlewares[i] != nil {
			handler = middlewares[i](handler)
		}
	}
	return handler
}

// ErrNilRouter is returned when a nil router is passed to a register function.
var ErrNilRouter = errors.New("protogen: router is nil")

// ErrNilHandler is returned when a nil handler is passed to a register function.
var ErrNilHandler = errors.New("protogen: handler is nil")

// DefaultRouter creates a new router with a new ServeMux.
//
// Deprecated: Use NewRouter(nil) instead.
func DefaultRouter() *RouteGroup {
	return NewRouter(nil)
}

// TaskServiceHandler is the interface for TaskService HTTP handlers.
type TaskServiceHandler interface {
	HandleCreateTask(w http.ResponseWriter, r *http.Request)
	HandleGetTask(w http.ResponseWriter, r *http.Request)
	HandleUpdateTask(w http.ResponseWriter, r *http.Request)
	HandleDeleteTask(w http.ResponseWriter, r *http.Request)
	HandleListTasks(w http.ResponseWriter, r *http.Request)
	HandleCompleteTask(w http.ResponseWriter, r *http.Request)
	HandleGetTasksByProject(w http.ResponseWriter, r *http.Request)
	HandleAssignTask(w http.ResponseWriter, r *http.Request)
}

// RegisterTaskServiceRoutes registers HTTP routes for TaskService.
// Returns an error if router or handler is nil.
func RegisterTaskServiceRoutes(r Routes, handler TaskServiceHandler) error {
	if r == nil {
		return ErrNilRouter
	}
	if handler == nil {
		return ErrNilHandler
	}
	r.HandleFunc(http.MethodPost, "/api/v1/tasks", handler.HandleCreateTask)
	r.HandleFunc(http.MethodGet, "/api/v1/tasks/{task_id}", handler.HandleGetTask)
	r.HandleFunc(http.MethodPut, "/api/v1/tasks/{task_id}", handler.HandleUpdateTask)
	r.HandleFunc(http.MethodPatch, "/api/v1/tasks/{task_id}", handler.HandleUpdateTask)
	r.HandleFunc(http.MethodDelete, "/api/v1/tasks/{task_id}", handler.HandleDeleteTask)
	r.HandleFunc(http.MethodGet, "/api/v1/tasks", handler.HandleListTasks)
	r.HandleFunc(http.MethodPost, "/api/v1/tasks/{task_id}/complete", handler.HandleCompleteTask)
	r.HandleFunc(http.MethodGet, "/api/v1/projects/{project_id}/tasks", handler.HandleGetTasksByProject)
	r.HandleFunc(http.MethodPost, "/api/v1/projects/{project_id}/tasks/{task_id}/assign/{user_id}", handler.HandleAssignTask)
	return nil
}

// MustRegisterTaskServiceRoutes registers HTTP routes for TaskService.
// Panics if router or handler is nil.
func MustRegisterTaskServiceRoutes(r Routes, handler TaskServiceHandler) {
	if err := RegisterTaskServiceRoutes(r, handler); err != nil {
		panic(err)
	}
}

// RegisterTaskServiceRoutes is a convenience method on RouteGroup.
//
// Deprecated: Use RegisterTaskServiceRoutes(router, handler) instead.
// This method does not return errors and will not work with Router interface from Group().
func (g *RouteGroup) RegisterTaskServiceRoutes(handler TaskServiceHandler) {
	_ = RegisterTaskServiceRoutes(g, handler)
}

// RegisterCreateTaskRoute registers the CreateTask handler.
// This registers all HTTP bindings for this method (1 binding(s)).
// Returns an error if router or handler is nil.
func RegisterCreateTaskRoute(r Routes, handler TaskServiceHandler, middlewares ...Middleware) error {
	if r == nil {
		return ErrNilRouter
	}
	if handler == nil {
		return ErrNilHandler
	}
	h := applyMiddlewares(http.HandlerFunc(handler.HandleCreateTask), middlewares)
	r.HandleFunc(http.MethodPost, "/api/v1/tasks", h.ServeHTTP)
	return nil
}

// RegisterCreateTask is a convenience method on RouteGroup.
//
// Deprecated: Use RegisterCreateTaskRoute(router, handler, middlewares...) instead.
// This method does not return errors and will not work with Router interface from Group().
func (g *RouteGroup) RegisterCreateTask(handler TaskServiceHandler, middlewares ...Middleware) {
	_ = RegisterCreateTaskRoute(g, handler, middlewares...)
}

// RegisterGetTaskRoute registers the GetTask handler.
// This registers all HTTP bindings for this method (1 binding(s)).
// Returns an error if router or handler is nil.
func RegisterGetTaskRoute(r Routes, handler TaskServiceHandler, middlewares ...Middleware) error {
	if r == nil {
		return ErrNilRouter
	}
	if handler == nil {
		return ErrNilHandler
	}
	h := applyMiddlewares(http.HandlerFunc(handler.HandleGetTask), middlewares)
	r.HandleFunc(http.MethodGet, "/api/v1/tasks/{task_id}", h.ServeHTTP)
	return nil
}

// RegisterGetTask is a convenience method on RouteGroup.
//
// Deprecated: Use RegisterGetTaskRoute(router, handler, middlewares...) instead.
// This method does not return errors and will not work with Router interface from Group().
func (g *RouteGroup) RegisterGetTask(handler TaskServiceHandler, middlewares ...Middleware) {
	_ = RegisterGetTaskRoute(g, handler, middlewares...)
}

// RegisterUpdateTaskRoute registers the UpdateTask handler.
// This registers all HTTP bindings for this method (2 binding(s)).
// Returns an error if router or handler is nil.
func RegisterUpdateTaskRoute(r Routes, handler TaskServiceHandler, middlewares ...Middleware) error {
	if r == nil {
		return ErrNilRouter
	}
	if handler == nil {
		return ErrNilHandler
	}
	h := applyMiddlewares(http.HandlerFunc(handler.HandleUpdateTask), middlewares)
	r.HandleFunc(http.MethodPut, "/api/v1/tasks/{task_id}", h.ServeHTTP)
	r.HandleFunc(http.MethodPatch, "/api/v1/tasks/{task_id}", h.ServeHTTP)
	return nil
}

// RegisterUpdateTask is a convenience method on RouteGroup.
//
// Deprecated: Use RegisterUpdateTaskRoute(router, handler, middlewares...) instead.
// This method does not return errors and will not work with Router interface from Group().
func (g *RouteGroup) RegisterUpdateTask(handler TaskServiceHandler, middlewares ...Middleware) {
	_ = RegisterUpdateTaskRoute(g, handler, middlewares...)
}

// RegisterDeleteTaskRoute registers the DeleteTask handler.
// This registers all HTTP bindings for this method (1 binding(s)).
// Returns an error if router or handler is nil.
func RegisterDeleteTaskRoute(r Routes, handler TaskServiceHandler, middlewares ...Middleware) error {
	if r == nil {
		return ErrNilRouter
	}
	if handler == nil {
		return ErrNilHandler
	}
	h := applyMiddlewares(http.HandlerFunc(handler.HandleDeleteTask), middlewares)
	r.HandleFunc(http.MethodDelete, "/api/v1/tasks/{task_id}", h.ServeHTTP)
	return nil
}

// RegisterDeleteTask is a convenience method on RouteGroup.
//
// Deprecated: Use RegisterDeleteTaskRoute(router, handler, middlewares...) instead.
// This method does not return errors and will not work with Router interface from Group().
func (g *RouteGroup) RegisterDeleteTask(handler TaskServiceHandler, middlewares ...Middleware) {
	_ = RegisterDeleteTaskRoute(g, handler, middlewares...)
}

// RegisterListTasksRoute registers the ListTasks handler.
// This registers all HTTP bindings for this method (1 binding(s)).
// Returns an error if router or handler is nil.
func RegisterListTasksRoute(r Routes, handler TaskServiceHandler, middlewares ...Middleware) error {
	if r == nil {
		return ErrNilRouter
	}
	if handler == nil {
		return ErrNilHandler
	}
	h := applyMiddlewares(http.HandlerFunc(handler.HandleListTasks), middlewares)
	r.HandleFunc(http.MethodGet, "/api/v1/tasks", h.ServeHTTP)
	return nil
}

// RegisterListTasks is a convenience method on RouteGroup.
//
// Deprecated: Use RegisterListTasksRoute(router, handler, middlewares...) instead.
// This method does not return errors and will not work with Router interface from Group().
func (g *RouteGroup) RegisterListTasks(handler TaskServiceHandler, middlewares ...Middleware) {
	_ = RegisterListTasksRoute(g, handler, middlewares...)
}

// RegisterCompleteTaskRoute registers the CompleteTask handler.
// This registers all HTTP bindings for this method (1 binding(s)).
// Returns an error if router or handler is nil.
func RegisterCompleteTaskRoute(r Routes, handler TaskServiceHandler, middlewares ...Middleware) error {
	if r == nil {
		return ErrNilRouter
	}
	if handler == nil {
		return ErrNilHandler
	}
	h := applyMiddlewares(http.HandlerFunc(handler.HandleCompleteTask), middlewares)
	r.HandleFunc(http.MethodPost, "/api/v1/tasks/{task_id}/complete", h.ServeHTTP)
	return nil
}

// RegisterCompleteTask is a convenience method on RouteGroup.
//
// Deprecated: Use RegisterCompleteTaskRoute(router, handler, middlewares...) instead.
// This method does not return errors and will not work with Router interface from Group().
func (g *RouteGroup) RegisterCompleteTask(handler TaskServiceHandler, middlewares ...Middleware) {
	_ = RegisterCompleteTaskRoute(g, handler, middlewares...)
}

// RegisterGetTasksByProjectRoute registers the GetTasksByProject handler.
// This registers all HTTP bindings for this method (1 binding(s)).
// Returns an error if router or handler is nil.
func RegisterGetTasksByProjectRoute(r Routes, handler TaskServiceHandler, middlewares ...Middleware) error {
	if r == nil {
		return ErrNilRouter
	}
	if handler == nil {
		return ErrNilHandler
	}
	h := applyMiddlewares(http.HandlerFunc(handler.HandleGetTasksByProject), middlewares)
	r.HandleFunc(http.MethodGet, "/api/v1/projects/{project_id}/tasks", h.ServeHTTP)
	return nil
}

// RegisterGetTasksByProject is a convenience method on RouteGroup.
//
// Deprecated: Use RegisterGetTasksByProjectRoute(router, handler, middlewares...) instead.
// This method does not return errors and will not work with Router interface from Group().
func (g *RouteGroup) RegisterGetTasksByProject(handler TaskServiceHandler, middlewares ...Middleware) {
	_ = RegisterGetTasksByProjectRoute(g, handler, middlewares...)
}

// RegisterAssignTaskRoute registers the AssignTask handler.
// This registers all HTTP bindings for this method (1 binding(s)).
// Returns an error if router or handler is nil.
func RegisterAssignTaskRoute(r Routes, handler TaskServiceHandler, middlewares ...Middleware) error {
	if r == nil {
		return ErrNilRouter
	}
	if handler == nil {
		return ErrNilHandler
	}
	h := applyMiddlewares(http.HandlerFunc(handler.HandleAssignTask), middlewares)
	r.HandleFunc(http.MethodPost, "/api/v1/projects/{project_id}/tasks/{task_id}/assign/{user_id}", h.ServeHTTP)
	return nil
}

// RegisterAssignTask is a convenience method on RouteGroup.
//
// Deprecated: Use RegisterAssignTaskRoute(router, handler, middlewares...) instead.
// This method does not return errors and will not work with Router interface from Group().
func (g *RouteGroup) RegisterAssignTask(handler TaskServiceHandler, middlewares ...Middleware) {
	_ = RegisterAssignTaskRoute(g, handler, middlewares...)
}
